// <auto-generated />
using System;
using KulturAtlasi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulturAtlasi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204203143_EtkilesimTablolari")]
    partial class EtkilesimTablolari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KulturAtlasi.Models.AktiviteKaydi", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int>("IcerikID")
                        .HasColumnType("int");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("LogID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("AktiviteKayitlari");
                });

            modelBuilder.Entity("KulturAtlasi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("GizliHesap")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilFotografiYolu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KulturAtlasi.Models.Begeni", b =>
                {
                    b.Property<int>("BegeniID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BegeniID"));

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaylasimID")
                        .HasColumnType("int");

                    b.HasKey("BegeniID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("PaylasimID");

                    b.ToTable("Begeniler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Bildirim", b =>
                {
                    b.Property<int>("BildirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimID"));

                    b.Property<bool>("GorulduMu")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BildirimID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Dizi", b =>
                {
                    b.Property<int>("DiziID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiziID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BaslangicYili")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BolumSayisi")
                        .HasColumnType("int");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KullaniciPuani")
                        .HasColumnType("int");

                    b.Property<string>("PosterYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SezonSayisi")
                        .HasColumnType("int");

                    b.Property<string>("Yonetmen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiziID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Diziler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Durum", b =>
                {
                    b.Property<int>("DurumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurumID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DurumID");

                    b.ToTable("Durumlar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Etiket", b =>
                {
                    b.Property<int>("EtiketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtiketID"));

                    b.Property<string>("EtiketAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("EtiketID");

                    b.ToTable("Etiketler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.EtiketliIcerik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EtiketID")
                        .HasColumnType("int");

                    b.Property<int>("IcerikID")
                        .HasColumnType("int");

                    b.Property<string>("IcerikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EtiketID");

                    b.ToTable("EtiketliIcerikler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KullaniciPuani")
                        .HasColumnType("int");

                    b.Property<string>("PosterYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.Property<string>("Yonetmen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Filmler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.GezilecekYer", b =>
                {
                    b.Property<int>("YerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YerID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotografYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KonumKoordinati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MekanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeyahatID")
                        .HasColumnType("int");

                    b.HasKey("YerID");

                    b.HasIndex("SeyahatID");

                    b.ToTable("GezilecekYerler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KapakResmiYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KullaniciPuani")
                        .HasColumnType("int");

                    b.Property<string>("Yazar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KitapID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.KullaniciRozeti", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RozetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerilmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("RozetID");

                    b.ToTable("KullaniciRozetleri");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Mesaj", b =>
                {
                    b.Property<int>("MesajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesajID"));

                    b.Property<string>("AliciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GonderenID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MesajID");

                    b.HasIndex("AliciID");

                    b.HasIndex("GonderenID");

                    b.ToTable("Mesajlar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Muzik", b =>
                {
                    b.Property<int>("MuzikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuzikID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Album")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinlemeLinki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<string>("KapakResmiYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KullaniciPuani")
                        .HasColumnType("int");

                    b.Property<string>("Sanatci")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("MuzikID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Muzikler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Oneri", b =>
                {
                    b.Property<int>("OneriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OneriID"));

                    b.Property<string>("IcerikTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OnerilenIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OneriID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Oneriler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Paylasim", b =>
                {
                    b.Property<int>("PaylasimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaylasimID"));

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IlgiliIcerikID")
                        .HasColumnType("int");

                    b.Property<string>("IlgiliIcerikTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaylasimTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("PaylasimID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Paylasimlar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Rozet", b =>
                {
                    b.Property<int>("RozetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RozetID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ikon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RozetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RozetID");

                    b.ToTable("Rozetler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Seyahat", b =>
                {
                    b.Property<int>("SeyahatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeyahatID"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Boylam")
                        .HasColumnType("float");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<double?>("Enlem")
                        .HasColumnType("float");

                    b.Property<string>("GeziNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZiyaretTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("SeyahatID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Seyahatler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Takip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TakipEdenID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TakipEdilenID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TakipTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TakipEdenID");

                    b.HasIndex("TakipEdilenID");

                    b.ToTable("Takipler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Yorum", b =>
                {
                    b.Property<int>("YorumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumID"));

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PaylasimID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("YorumID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("PaylasimID");

                    b.ToTable("Yorumlar");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KulturAtlasi.Models.AktiviteKaydi", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("AktiviteKayitlari")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Begeni", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Begeniler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.Paylasim", "Paylasim")
                        .WithMany("Begeniler")
                        .HasForeignKey("PaylasimID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Paylasim");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Bildirim", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Dizi", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Diziler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.EtiketliIcerik", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Etiket", "Etiket")
                        .WithMany("EtiketliIcerikler")
                        .HasForeignKey("EtiketID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Etiket");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Film", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Durum", "Durum")
                        .WithMany("Filmler")
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Filmler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.GezilecekYer", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Seyahat", "Seyahat")
                        .WithMany("GezilecekYerler")
                        .HasForeignKey("SeyahatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seyahat");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Kitap", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Durum", "Durum")
                        .WithMany("Kitaplar")
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.KullaniciRozeti", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("KullaniciRozetleri")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.Rozet", "Rozet")
                        .WithMany("KullaniciRozetleri")
                        .HasForeignKey("RozetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rozet");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Mesaj", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Alici")
                        .WithMany("AlinanMesajlar")
                        .HasForeignKey("AliciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Gonderen")
                        .WithMany("GonderilenMesajlar")
                        .HasForeignKey("GonderenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("Gonderen");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Muzik", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Muzikler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Oneri", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Oneriler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Paylasim", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Paylasimlar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Seyahat", b =>
                {
                    b.HasOne("KulturAtlasi.Models.Durum", "Durum")
                        .WithMany("Seyahatler")
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Seyahatler")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Takip", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "TakipEden")
                        .WithMany()
                        .HasForeignKey("TakipEdenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "TakipEdilen")
                        .WithMany()
                        .HasForeignKey("TakipEdilenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TakipEden");

                    b.Navigation("TakipEdilen");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Yorum", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", "Kullanici")
                        .WithMany("Yorumlar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.Paylasim", "Paylasim")
                        .WithMany("Yorumlar")
                        .HasForeignKey("PaylasimID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Paylasim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KulturAtlasi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KulturAtlasi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KulturAtlasi.Models.ApplicationUser", b =>
                {
                    b.Navigation("AktiviteKayitlari");

                    b.Navigation("AlinanMesajlar");

                    b.Navigation("Begeniler");

                    b.Navigation("Bildirimler");

                    b.Navigation("Diziler");

                    b.Navigation("Filmler");

                    b.Navigation("GonderilenMesajlar");

                    b.Navigation("Kitaplar");

                    b.Navigation("KullaniciRozetleri");

                    b.Navigation("Muzikler");

                    b.Navigation("Oneriler");

                    b.Navigation("Paylasimlar");

                    b.Navigation("Seyahatler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Durum", b =>
                {
                    b.Navigation("Filmler");

                    b.Navigation("Kitaplar");

                    b.Navigation("Seyahatler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Etiket", b =>
                {
                    b.Navigation("EtiketliIcerikler");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Paylasim", b =>
                {
                    b.Navigation("Begeniler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Rozet", b =>
                {
                    b.Navigation("KullaniciRozetleri");
                });

            modelBuilder.Entity("KulturAtlasi.Models.Seyahat", b =>
                {
                    b.Navigation("GezilecekYerler");
                });
#pragma warning restore 612, 618
        }
    }
}
